// <auto-generated />
namespace AssetTrackingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_role_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_role_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201610291444326_user_role_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
